In [4]:
lista=[]

while True:
    
    numero = int(input("Digite um número de 1 a 10 (para sair digite 0): "))
    
    if numero==0:
        break
    
    if numero>10 or numero <0:
        print("Você digitou um número inválido")
        continue

    if numero%2==0:
        lista.append(numero)

if not lista:
    print("Você não digitou nenhum número par")

else:
    print(f'Você digitou {len(lista)} número pares')

Você não digitou nenhum número par


In [ ]:
preco_tecnologia={"notebook asus":2450, "iphone":4500, "samsung galaxy":3000, "tv samsung": 1000,"ps5":3000, "tablet": 1000, "notebook dell": 3000, "ipad":300, "tv philco":800, "notebook hp":1700}


def maiorque2000(item):
    return item[1]>2000

def menorque2000(item):
    return item[1]<2000

produtos_acima2000 = dict(list(filter(maiorque2000, preco_tecnologia.items())))
print(produtos_acima2000)


produtos_abaixo2000 = dict(list(filter(menorque2000,preco_tecnologia.items())))
print(produtos_abaixo2000)


'''
#Outra maneira de fazer usando lambda not que vai pegar os itens que foram recusados pela função 'maiorque2000'

produtos_abaixo2000=dict(list(filter(lambda item: not maiorque2000(item), preco_tecnologia.items())))
print(produtos_abaixo2000)

'''




{'notebook asus': 2450, 'iphone': 4500, 'samsung galaxy': 3000, 'ps5': 3000, 'notebook dell': 3000}
{'tv samsung': 1000, 'tablet': 1000, 'ipad': 300, 'tv philco': 800, 'notebook hp': 1700}


In [21]:
preco_tecnologia={"notebook asus":2450, "iphone":4500, "samsung galaxy":3000, "tv samsung": 1000,"ps5":3000, "tablet": 1000, "notebook dell": 3000, "ipad":300, "tv philco":800, "notebook hp":1700}

def imposto(item):
    produto=item[0]
    preco_impostado = round(item[1]*1.10,2)
    return (produto,preco_impostado)

produtos_com_imposto = dict(map(imposto,preco_tecnologia.items()))
print(produtos_com_imposto)

{'notebook asus': 2695.0, 'iphone': 4950.0, 'samsung galaxy': 3300.0, 'tv samsung': 1100.0, 'ps5': 3300.0, 'tablet': 1100.0, 'notebook dell': 3300.0, 'ipad': 330.0, 'tv philco': 880.0, 'notebook hp': 1870.0}


In [ ]:
preco_tecnologia={"notebook asus":2450, "iphone":4500, "samsung galaxy":3000, "tv samsung": 1000,"ps5":3000, "tablet": 1000, "notebook dell": 3000, "ipad":300, "tv philco":800, "notebook hp":1700}

def calcular_imposto(imposto):
    return lambda preco: round(preco*imposto,2)

#produto 0.1
#serviço 0.15
#royalties 0.25

calcular_preco_produto = calcular_imposto(0.1)
calcular_preco_servico = calcular_imposto(0.15)
calcular_preco_royalties = calcular_imposto(0.25)

'''
print(calcular_preco_produto(100))

print(calcular_preco_servico(100))

print(calcular_preco_royalties(100))
'''

'''
def aplicar_imposto(item):
    produto,preco=item

    preco_total = preco + calcular_preco_produto(preco)+calcular_preco_servico(preco)+calcular_preco_royalties(preco)

    return (produto,preco_total)


produtos_com_imp = dict(map(aplicar_imposto,preco_tecnologia.items()))
print(produtos_com_imp)

'''






{'notebook asus': 3675.0, 'iphone': 6750.0, 'samsung galaxy': 4500.0, 'tv samsung': 1500.0, 'ps5': 4500.0, 'tablet': 1500.0, 'notebook dell': 4500.0, 'ipad': 450.0, 'tv philco': 1200.0, 'notebook hp': 2550.0}


In [41]:
import numpy as np

array = np.array([1,2,3,4,5])
novo_array=array+1
print(novo_array)

lista = [1,2,3,4,5]

nova_lista=[]
for numero in lista:
    nova_lista.append(numero+1)

print(nova_lista)
'''
Experimento com calculo matricial


A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

soma = A+B
subtracao = A-B

mult_elemento = A*B
produto = A@B

inversa = np.linalg.inv(A)
det = round(np.linalg.det(A),2)

tranposta = np.transpose(A)

lista_de_operacoes=[soma,subtracao,mult_elemento,produto,inversa,det,tranposta]

for item in lista_de_operacoes:
    print(f'\n{item}\n')

'''

[2 3 4 5 6]
[2, 3, 4, 5, 6]


"\nExperimento com calculo matricial\n\n\nA = np.array([[1,2], [3,4]])\nB = np.array([[5,6], [7,8]])\n\nsoma = A+B\nsubtracao = A-B\n\nmult_elemento = A*B\nproduto = A@B\n\ninversa = np.linalg.inv(A)\ndet = round(np.linalg.det(A),2)\n\ntranposta = np.transpose(A)\n\nlista_de_operacoes=[soma,subtracao,mult_elemento,produto,inversa,det,tranposta]\n\nfor item in lista_de_operacoes:\n    print(f'\n{item}\n')\n\n"

In [49]:
import numpy as np
import time

lista = list(range(1,100_000_001))
array = np.array(range(1,100_000_001))

#calcule a soma de todos os números na lista

inicio = time.time()
soma_lista = sum(lista)
fim = time.time()

tempo1=fim-inicio

print(f"O tempo para somar todos os elementos da lista foi {fim - inicio} segundos")

#Calcular todos os elementos do array

inicio = time.time()
soma_array = np.sum(array)
fim = time.time()
tempo2=fim-inicio


print(f"O tempo para somar todos os elementos da lista foi {fim - inicio} segundos")


#Razão entre os tempos
razao=tempo1/tempo2
print(f"O tempo necessário para somar os elementos em array foi cerca de {razao:.2f} vezes mais rapido que para somar os elementos da lista")

O tempo para somar todos os elementos da lista foi 11.005642414093018 segundos
O tempo para somar todos os elementos da lista foi 1.0100464820861816 segundos
O tempo necessário para somar os elementos em array foi cerca de 10.90 vezes mais rapido que para somar os elementos da lista


In [ ]:
#Testes com slice 

array = np.array(["a","b","c","d","e"])

for i in range (len(array)):
    print(f'\n{array[i]}\n')

'''
print(f'\n{array[-1]}\n')

print(array[1:4])

print(array[0:4])

print(array[0:-1])

print(array[0:4:3])


print(array[0::2])
print(array[::2])
print(array[::])
print(array[0::-1])
'''

In [74]:
#Preços com array

import numpy as np

#Preços dos produtos
precos = np.array([20,25,30,35,40])

#Aumentar os preços em 10%
novos_precos = precos * 1.10
print(novos_precos)



[22.  27.5 33.  38.5 44. ]


In [75]:
#Np para somas 

import numpy as np 

#Vendas do Dia

vendas = np.array([200,220,250,210,300])

#Somar todas as vendas 

total_vendas = np.sum(vendas)
print(total_vendas)

1180


In [76]:
#Relatórinho de vendas 

import numpy as np 

#Preços dos produtos 

precos = np.array([20,25,30,35,40])

#Enontrar o produto mais caro e mais barato

produto_mais_caro = np.max(precos)
produto_mais_barato = np.min(precos)
print(produto_mais_caro,produto_mais_barato)
print(f"O produto mais caro: {produto_mais_caro}")
print(f"O produto mais barato: {produto_mais_barato}")

40 20
O produto mais caro: 40
O produto mais barato: 20


In [89]:
#rOrdenar em ordem de preço de compra

import numpy as np

#Vendas diárias
vendas = np.array([200,220,250,210,300])

#Ordenar as vendas
vendas_ordenas = np.sort(vendas)
print(vendas_ordenas)

[200 210 220 250 300]


In [90]:
#Vendas de Produtos 

import numpy as np


#Números de produtos vendidos

quantidades = np.array([10,20,30,40])

#Preços dos produtos

precos = np.array([5,10,15,20])

#Valor total de vendas 

print(quantidades * precos)

#Valor total arrecadado

print(f'O valor total arrecado com as vedas foi: R$ {np.sum(quantidades*precos)} reais')

#Métodos alternativo

total_vendas = np.dot(quantidades,precos)
print(total_vendas)

[ 50 200 450 800]
O valor total arrecado com as vedas foi: R$ 1500 reais
1500


In [ ]:
#Random 

import numpy as np

#Crie um gerador de números aleatórios 
rng = np.random.default_rng()

numero_aleatorio = rng.random()
print(numero_aleatorio)

#-----------------------------------

array_aleatorio = rng.random(3)
print(array_aleatorio)

print(np.round(array_aleatorio*10,2))

0.8465005808263548
[0.70754379 0.87220981 0.44476687]
[7. 9. 4.]


In [ ]:
#Gerador de dados aleatórios para um teste

import numpy as np

#Gere dads de venas falsos para 30 dias
#Vamos supor que as vendas de um produto podem variar de 50 a 200 por dia

rng = np.random.default_rng(seed=42)
dados_vendas = rng.integers(low = 50, high=200, size=30)
print(dados_vendas)

#Operações para essas vendas 

media = np.round(np.mean(dados_vendas),2)
maximo = np.max(dados_vendas)
minimo = np.min(dados_vendas)
mediana = np.median(dados_vendas)
percentil = np.percentile(dados_vendas,50)
desvio_padrao = np.round(np.std(dados_vendas),2)
variancia = np.round(np.var(dados_vendas),2)

dia_max = np.argmax(dados_vendas)+1
dia_menos = np.argmin(dados_vendas)+1

print(f"O dia com mais vendas foi o dia {dia_max} com {maximo} vendas.")
print(f"O dia com menos vendas foi o dia {dia_menos} com {minimo} vendas.")
print(f'A média de vendas no mês foi {media}')
print(f"O valor da mediana das vendas é {mediana}")
print(f"O valor de percenti é {percentil}")
print(f"O desvio padrão é {desvio_padrao}")
print(f"A variancia é {variancia}")


[ 63 166 148 115 114 178  62 154  80  64 128 196 160 164 157 167 126  69
 175 117 125 105  77 189 167 146 110 173 131 116]
O dia com mais vendas foi o dia 12 com 196 vendas.
O dia com menos vendas foi o dia 7 com 62 vendas.
A média de vendas no mês foi 131.4
O valor da mediana das vendas é 129.5
O valor de percenti é 129.5
O desvio padrão é 39.31
A variancia é 1544.9066666666665


In [134]:
#Exercicios com salarios

import numpy as np

#Salários dos funcionários

salarios = np.array([3000,3500,4000,2000,4500,4000,5000])

#Calcular a média salarial

media_salarial = np.round(np.mean(salarios),2)
print(f"A média salarial é R$ {media_salarial}")

#Identificar salarios acima da media 
funcionarios_acima_media = np.where(salarios>media_salarial)[0]
print(f"Os funcionários com salários acima da média são {funcionarios_acima_media}")
print(f"Os salarios acima da media são {salarios[funcionarios_acima_media]} ")

#Dizer se o salario é acima ou abaixo da media 
print(np.where(salarios>media_salarial,'Acima da média','Abaixo da média'))

#Salarios bônus
salarios_bonus=np.where(salarios<media_salarial,salarios*1.1,salarios)
print(salarios)
print(salarios_bonus)

#Salarios na faixa de 3000 e 4500
print(np.where((salarios>=3000) & (salarios<=4500)))

#Reajuste salarial de 5% para esses que estão dentro dessa faixa 
print(salarios)
print(np.where((salarios>=3000) & (salarios<=4500),salarios*1.05,salarios))

#Reajuste salarial de 10% para pessoas abaixo de 3000 ou acima de 4500
print(salarios)
salarios_ajustados = np.where((salarios<3000) | (salarios>4500),salarios*1.1,salarios)
print(salarios_ajustados)


A média salarial é R$ 3714.29
Os funcionários com salários acima da média são [2 4 5 6]
Os salarios acima da media são [4000 4500 4000 5000] 
['Abaixo da média' 'Abaixo da média' 'Acima da média' 'Abaixo da média'
 'Acima da média' 'Acima da média' 'Acima da média']
[3000 3500 4000 2000 4500 4000 5000]
[3300. 3850. 4000. 2200. 4500. 4000. 5000.]
(array([0, 1, 2, 4, 5]),)
[3000 3500 4000 2000 4500 4000 5000]
[3150. 3675. 4200. 2000. 4725. 4200. 5000.]
[3000 3500 4000 2000 4500 4000 5000]
[3000. 3500. 4000. 2200. 4500. 4000. 5500.]


In [143]:
#Reshape de um array

import numpy as np

#Vendas diarias para 2 semanas

vendas = np.array ([200,220,250,210,300,280,230,210,220,240,230,210,280,220])

#Reorganizar os dados em uma matriz de 2x7

vendas_reshaped = np.reshape(vendas,(2,7))
print(vendas_reshaped)

#Operações com o formato da matriz
print(vendas.ndim)
print(vendas.shape)

print(vendas_reshaped.ndim)
print(vendas_reshaped.shape)

#Printando cada matriz de venda separadamente
print(vendas_reshaped[0])

print(vendas_reshaped[1])

#Soma de cada array

print(vendas_reshaped.sum())

print(vendas_reshaped.sum(axis=1))
print(vendas_reshaped.mean(axis=1))



[[200 220 250 210 300 280 230]
 [210 220 240 230 210 280 220]]
1
(14,)
2
(2, 7)
[200 220 250 210 300 280 230]
[210 220 240 230 210 280 220]
3300
[1690 1610]
[241.42857143 230.        ]
